name: analog

services:
  db:
    container_name: analog_db
    image: bitnami/postgresql:15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - analog_network

volumes:
  postgres_data:

networks:
  analog_network:
    driver: bridge
